// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Scavolini.Database
{
    public partial class Comuni
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CodiceRegione { get; set; }
        public string Cap { get; set; }
    }
}