// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Scavolini.Database
{
    public partial class ScavolinidatabaseContext : DbContext
    {
        public ScavolinidatabaseContext()
        {
        }

        public ScavolinidatabaseContext(DbContextOptions<ScavolinidatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Comuni> Comuni { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=ScavoliniDatabase;Integrated Security=true");

            modelBuilder.Entity<Comuni>(entity =>
            {
                entity.Property(e => e.Cap)
                    .IsRequired()
                    .HasMaxLength(6)
                    .IsUnicode(false);

                entity.Property(e => e.CodiceRegione)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}